### ISSUE TITLE
Django page is saying I do not have any URLs configured

### ISSUE THREAD

**Issue by shakzoola** [hackers-friend/HackersFriend-NewsAggregator#1]
I am trying to make a COVID19 news aggregator and have been working with two websites for now. 'https://www.usatoday.com/search/?q=COVID19'
'https://www.nytimes.com/2020/09/11/world/covid-19-coronavirus.html' 

After going through the tutorial I am getting a message that says I have not configured URLs. Can you help me with this problem?

**Comment by irajankumar** [comment]
Have you wrote your url paths in urls.py file ?

Share more details.

**Comment by irajankumar** [comment]
Closing the issue, as we didn't receive any response. Feel free to create new issue if there's any more.
